### ISSUE TITLE
Collect github data with prometheus and show in grafana

### ISSUE THREAD

**Issue by schwesig** [open-services-group/scrum#40]
- [x] create a mockup: what data needs to be displayed, and how --> https://github.com/open-services-group/scrum/issues/40#issuecomment-1235596924
- [x] collect data via prometheus (prom ql) --> https://github.com/open-services-group/scrum/issues/40#issuecomment-1235602090
- [x] create a grafana dashboard, following the mockup --> https://github.com/open-services-group/scrum/issues/40#issuecomment-1235604477
- [x] deploy apps/grafana/overlays/moc/smaug-public/ --> https://grafana-public.operate-first.cloud/ (https://github.com/operate-first/apps/pull/2367)

**Comment by schwesig** [comment]
create mockup
![image](https://user-images.githubusercontent.com/89909507/188175725-f6b4889d-595d-4950-a085-5d574bdd6422.png)
![image](https://user-images.githubusercontent.com/89909507/188175954-a47f0c8b-64e0-4d85-88f7-c5230f310ee5.png)

**Comment by schwesig** [comment]
## promql
- decision for last 4 days:
  - 30 days can take some time to collect
  - so far 4 days (or a week) seem to get fairly fast results
  - wasn't able to pull more data than last 2 days (tbd)

- Project Owner Groups, last 4 days, last
  - count(count by (annotation_op1st_project_owner) (k8s_resource_annotations_info{annotation_op1st_project_owner!=""}))

- Projects, last 4 days, last
  - count(count by (annotation_openshift_io_display_name) (k8s_resource_annotations_info{annotation_openshift_io_display_name!=""}))

- Namespaces, last 4 days, last
  - count(count by (name) (k8s_resource_annotations_info{name!="", annotation_openshift_io_display_name!=""}))

- Projects per Product Owner Group, last 4 days, last
  - (count(k8s_resource_annotations_info{annotation_op1st_project_owner!=""}) by (annotation_op1st_project_owner))

**Comment by schwesig** [comment]
example: 
json for Project Owner Groups, last 4 days, last

```
{
  "id": 4,
  "gridPos": {
    "h": 6,
    "w": 4,
    "x": 0,
    "y": 10
  },
  "type": "stat",
  "title": "Project Owner Groups, last 4 days, last",
  "datasource": {
    "uid": "PDD709D2516BFAE8A",
    "type": "prometheus"
  },
  "pluginVersion": "8.4.3",
  "description": "Project Owner Groups, last 4 days, last",
  "fieldConfig": {
    "defaults": {
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "#ffffff",
            "value": null
          }
        ]
      },
      "color": {
        "mode": "thresholds"
      },
      "unit": ""
    },
    "overrides": []
  },
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "last"
      ],
      "fields": ""
    },
    "orientation": "horizontal",
    "textMode": "auto",
    "colorMode": "none",
    "graphMode": "area",
    "justifyMode": "auto"
  },
  "targets": [
    {
      "expr": "count(count by (annotation_op1st_project_owner) (k8s_resource_annotations_info{annotation_op1st_project_owner!=\"\"}))",
      "legendFormat": "Verbose",
      "interval": "",
      "exemplar": false,
      "datasource": {
        "type": "prometheus",
        "uid": "PDD709D2516BFAE8A"
      },
      "refId": "A"
    }
  ]
}
```

**Comment by schwesig** [comment]
dashboard
snapshot
https://grafana.operate-first.cloud/dashboard/snapshot/2I4k71DpSz3wvIWvvnT2eSi08XyVH71N

**Comment by schwesig** [comment]
/close
cleanup after change of organisation
